apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    type: testytpe
    app: basicauth
spec:
  containers:
  - name: testpod
    image: httpd:latest
    resources:
      requests: 
        cpu: "500m"
        memory: "200Mi"
      limits:
        memory: "800Mi"
        cpu: "900m"
    ports:
      - containerPort: 80
