apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-data-0
  namespace: wordpress
  labels:
    app: wordpress
    component: wordpress
    application: wp-app
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce