apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-app-storage
  labels:
    app: mysql-app
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /container_data/server1
    server: 172.31.40.140

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-app-data-vol
  namespace: mysql
  labels: 
    app: mysql-app
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

