apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web1-ingress
  namespace: default  
  labels:
    app: web1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2  
spec:
  ingressClassName: nginx
  rules:
  - host: api.ocelottraining.com
    http:
      paths:
      - pathType: Prefix
        path: /web1
        backend:
          service:
            name: web1
            port: 
              number: 80
