apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web2-ingress
  namespace: web2  
  labels:
    app: web2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  
spec:
  ingressClassName: nginx
  rules:
  - host: api.mgmt.ocelottraining.com
    http:
      paths:
      - pathType: Prefix
        path: /web2
        backend:
          service:
            name: web2
            port: 
              number: 80
  - host: web2.mgmt.ocelottraining.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: web2
            port: 
              number: 80            