apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web3-ingress
  namespace: web3
  labels:
    app: web3
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  
spec:
  ingressClassName: nginx
  rules:
  - host: api.mgmt.ocelottraining.com
    http:
      paths:
      - pathType: Prefix
        path: /web3
        backend:
          service:
            name: web3
            port: 
              number: 80
  - host: web3.mgmt.ocelottraining.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: web3
            port: 
              number: 80            