apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-volume
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nfs-slow-sc
  accessModes:
    - ReadWriteOnce
